version: '3'

services:
  graphql:
    image: 879005436101.dkr.ecr.us-east-2.amazonaws.com/graphql-server:0.0.1
    container_name: graphql-server
    command: npm run serve
    ports:
      - '8080:8080'
    depends_on:
      - api
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:8080/healthcheck',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
  api:
    image: 879005436101.dkr.ecr.us-east-2.amazonaws.com/api-server:0.0.2
    container_name: api-server
    command: npm run start
    ports:
      - '3000:3000'
